### ISSUE TITLE
Update documentation for NFS and Samba

### ISSUE THREAD

**Issue by vinima** [rockstor/rockstor-doc#103] opened 2015-11-02 19:47 UTC
Old documentation for NFS and Samba needs to be updated.

**Comment by phillxnet** [comment] 2019-02-09 16:33
Closing as partial duplicate of:
"Connecting to shares via CIFS and NFS" #16
and
"Add how-to for Samba access from different clients" #110
@vinima Thanks for opening this originally, I'm just trying to manage (read reduce) our backlog into more tightly defined issues. Hope all is well with you.

**Closed by phillxnet** 2019-02-09 16:33 UTC
