### ISSUE TITLE
Update clients.rst (accessing shares from clients)

### ISSUE THREAD

**Issue by priyaganti** [rockstor/rockstor-doc#33] opened 2014-02-22 00:54 UTC
1. Access shares via samba/CIFS on Windows
2. Accessing NFS shares

**Comment by phillxnet** [comment] 2016-01-24 16:01
@schakrava I suggest this be closed as a (mostly) duplicate of #16 "Connecting to shares via CIFS and NFS"

**Comment by schakrava** [comment] 2016-01-24 21:32
Good point @phillxnet . Thanks!

**Closed by schakrava** 2016-01-24 21:32 UTC
